JAVA - CICD POC

diff --git a/.github/workflows/javaCD.yml b/.github/workflows/javaCD.yml
--- a/.github/workflows/javaCD.yml
+++ b/.github/workflows/javaCD.yml
@@ -46,8 +46,14 @@ jobs:
         id: checkov_scan
         run: |
           # Install Checkov
-          curl -sSL https://github.com/bridgecrewio/checkov/releases/download/v2.0.0/checkov_2.0.0_linux_amd64.tar.gz | tar -xz -C /usr/local/bin
-          
+          echo "Downloading Checkov..."
+          curl -sSL https://github.com/bridgecrewio/checkov/releases/download/v2.0.0/checkov_2.0.0_linux_amd64.tar.gz -o checkov.tar.gz
+          if [ $? -eq 0 ]; then
+            tar -xzvf checkov.tar.gz -C /usr/local/bin
+          else
+            echo "Error downloading Checkov"
+            exit 1
+          fi
           # Run Checkov for Helm chart static analysis
           checkov -d ./demo-app -o json > checkov_report.json || true  # The 'true' ensures the pipeline continues even if Checkov finds issues.
 
